=== slabymil/xslam043/katalog.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
  <xs:element name="katalog">
    <xs:complexType mixed="true">
      <xs:sequence>
        <xs:element minOccurs="0" maxOccurs="unbounded" ref="notebook"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="notebook">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="Vyrobce"/>
        <xs:element ref="Typ"/>
        <xs:element ref="Barva"/>
        <xs:element ref="Prodej"/>
        <xs:element ref="Displej"/>
        <xs:element ref="Rozmery"/>
        <xs:element ref="Hmotnost"/>
        <xs:element ref="Baterie"/>
        <xs:element ref="Vykon"/>
        <xs:element ref="Vystupy"/>
        <xs:element ref="Vybava"/>
        <xs:element ref="OS"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="Vyrobce" type="xs:NCName"/>
  <xs:element name="Typ" type="xs:string"/>
  <xs:element name="Barva" type="xs:NCName"/>
  <xs:element name="Prodej">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="Cena"/>
        <xs:element ref="Alza"/>
        <xs:element ref="Mall"/>
        <xs:element ref="CZC.cz"/>
        <xs:element ref="Datart"/>
        <xs:element ref="Mironet"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="Cena">
    <xs:complexType>
      <xs:simpleContent>
        <xs:extension base="xs:integer">
          <xs:attribute name="mena" use="required" type="xs:NCName"/>
        </xs:extension>
      </xs:simpleContent>
    </xs:complexType>
  </xs:element>
  <xs:element name="Alza" type="xs:NCName"/>
  <xs:element name="Mall" type="xs:NCName"/>
  <xs:element name="CZC.cz" type="xs:NCName"/>
  <xs:element name="Datart" type="xs:NCName"/>
  <xs:element name="Mironet" type="xs:NCName"/>
  <xs:element name="Displej">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="Uhlopricka"/>
        <xs:element ref="Rozliseni"/>
        <xs:element ref="TypPanelu"/>
        <xs:element ref="TypDispleje"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="Uhlopricka" type="xs:string"/>
  <xs:element name="Rozliseni" type="xs:NMTOKEN"/>
  <xs:element name="TypPanelu" type="xs:NCName"/>
  <xs:element name="TypDispleje" type="xs:NCName"/>
  <xs:element name="Rozmery">
    <xs:complexType>
      <xs:attribute name="Hloubka" use="required" type="xs:decimal"/>
      <xs:attribute name="Výška" use="required" type="xs:decimal"/>
      <xs:attribute name="Šířka" use="required" type="xs:integer"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="Hmotnost">
    <xs:complexType>
      <xs:attribute name="Hmotnost" use="required" type="xs:integer"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="Baterie">
    <xs:complexType>
      <xs:attribute name="Kapacita" use="required" type="xs:integer"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="Vykon">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="FrekvenceProcesoru"/>
        <xs:element ref="PocetJader"/>
        <xs:element ref="TypProcesoru"/>
        <xs:element ref="PametRAM"/>
        <xs:element ref="TypPameti"/>
        <xs:element ref="Harddisk"/>
        <xs:element ref="TypHDD"/>
        <xs:element ref="GrafickaKarta"/>
        <xs:element ref="TypGrafiky"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="FrekvenceProcesoru">
    <xs:complexType>
      <xs:simpleContent>
        <xs:extension base="xs:integer">
          <xs:attribute name="jednotky" use="required" type="xs:NCName"/>
        </xs:extension>
      </xs:simpleContent>
    </xs:complexType>
  </xs:element>
  <xs:element name="PocetJader">
    <xs:complexType>
      <xs:simpleContent>
        <xs:extension base="xs:integer">
          <xs:attribute name="rozmezi" use="required" type="xs:NMTOKEN"/>
        </xs:extension>
      </xs:simpleContent>
    </xs:complexType>
  </xs:element>
  <xs:element name="TypProcesoru">
    <xs:complexType mixed="true">
      <xs:attribute name="vyrobce" use="required" type="xs:NCName"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="PametRAM">
    <xs:complexType>
      <xs:simpleContent>
        <xs:extension base="xs:integer">
          <xs:attribute name="velikost" use="required" type="xs:NCName"/>
        </xs:extension>
      </xs:simpleContent>
    </xs:complexType>
  </xs:element>
  <xs:element name="TypPameti" type="xs:NCName"/>
  <xs:element name="Harddisk">
    <xs:complexType>
      <xs:simpleContent>
        <xs:extension base="xs:integer">
          <xs:attribute name="velikost" use="required" type="xs:NCName"/>
        </xs:extension>
      </xs:simpleContent>
    </xs:complexType>
  </xs:element>
  <xs:element name="TypHDD" type="xs:string"/>
  <xs:element name="GrafickaKarta">
    <xs:complexType>
      <xs:simpleContent>
        <xs:extension base="xs:integer">
          <xs:attribute name="velikost" use="required" type="xs:NCName"/>
        </xs:extension>
      </xs:simpleContent>
    </xs:complexType>
  </xs:element>
  <xs:element name="TypGrafiky" type="xs:NCName"/>
  <xs:element name="Vystupy">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="USB2.0"/>
        <xs:element ref="USB3.0"/>
        <xs:element ref="HDMI"/>
        <xs:element ref="DVI"/>
        <xs:element ref="VGA"/>
        <xs:element ref="Jack3.5mm"/>
        <xs:element ref="LAN"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="USB2.0" type="xs:NCName"/>
  <xs:element name="USB3.0" type="xs:NCName"/>
  <xs:element name="HDMI" type="xs:NCName"/>
  <xs:element name="DVI" type="xs:NCName"/>
  <xs:element name="VGA" type="xs:NCName"/>
  <xs:element name="Jack3.5mm" type="xs:NCName"/>
  <xs:element name="LAN" type="xs:NCName"/>
  <xs:element name="Vybava">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="Wifi"/>
        <xs:element ref="Bluetooth"/>
        <xs:element ref="OperacniSystem"/>
        <xs:element ref="PodsvicenaKlavesnice"/>
        <xs:element ref="CteckaKaret"/>
        <xs:element ref="NumerickaKlavesnice"/>
        <xs:element ref="OptickaMechanika"/>
        <xs:element ref="CteckaOtiskuPrstu"/>
        <xs:element ref="DotykovyDisplej"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="Wifi" type="xs:NCName"/>
  <xs:element name="Bluetooth" type="xs:NCName"/>
  <xs:element name="OperacniSystem" type="xs:NCName"/>
  <xs:element name="PodsvicenaKlavesnice" type="xs:NCName"/>
  <xs:element name="CteckaKaret" type="xs:NCName"/>
  <xs:element name="NumerickaKlavesnice" type="xs:NCName"/>
  <xs:element name="OptickaMechanika" type="xs:NCName"/>
  <xs:element name="CteckaOtiskuPrstu" type="xs:NCName"/>
  <xs:element name="DotykovyDisplej" type="xs:NCName"/>
  <xs:element name="OS">
    <xs:complexType>
      <xs:attribute name="TypOS" use="required" type="xs:NCName"/>
      <xs:attribute name="VerzeOS" use="required"/>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== slabymil/xslam043/katalog.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="katalog.xsl"?>
<katalog> xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="katalog.xsd">
    <notebook>
    	<Vyrobce>Acer</Vyrobce>
    	<Typ>Aspire F15 Black Aluminium</Typ>
        <Barva>černá</Barva>
    	<Prodej>
    		<Cena mena="Kč">19990</Cena>
    		<Alza>ano</Alza>
    		<Mall>ano</Mall>
    		<CZC.cz>ano</CZC.cz>
    		<Datart>ano</Datart>
    		<Mironet>ne</Mironet>
    	</Prodej>
    	<Displej>
    	    <Uhlopricka>15.6</Uhlopricka>
    	    <Rozliseni>1920x1080</Rozliseni>
    		<TypPanelu>IPS</TypPanelu>
    	    <TypDispleje>Matný</TypDispleje>
    	</Displej>
        <Rozmery Výška="29.2" Šířka="381" Hloubka="256"/>
    	<Hmotnost Hmotnost="2400"/>
    	<Baterie Kapacita="62"/>
    	<Vykon>
    	    <FrekvenceProcesoru jednotky="mHz">2500</FrekvenceProcesoru>
    		<PocetJader rozmezi="1-8">2</PocetJader>
    	    <TypProcesoru vyrobce="Intel">Intel Core i7 7500U</TypProcesoru>
    		<PametRAM velikost="GB">8</PametRAM>
    		<TypPameti>DDR4</TypPameti>
    		<Harddisk velikost="GB">1128</Harddisk>
    		<TypHDD>HDD + SSD</TypHDD>
    		<GrafickaKarta velikost="GB">4</GrafickaKarta>
    		<TypGrafiky>NVIDEA</TypGrafiky>
    	</Vykon>
    	<Vystupy>
    		<USB2.0>ano</USB2.0>
    		<USB3.0>ano</USB3.0>
    		<HDMI>ano</HDMI>
    		<DVI>ne</DVI>
    		<VGA>ano</VGA>
    		<Jack3.5mm>ano</Jack3.5mm>
    		<LAN>ano</LAN>
    	</Vystupy>
    	<Vybava>
    		<Wifi>ano</Wifi>
    		<Bluetooth>ano</Bluetooth>
    		<OperacniSystem>ano</OperacniSystem>
    		<PodsvicenaKlavesnice>ne</PodsvicenaKlavesnice>
    		<CteckaKaret>ano</CteckaKaret>
    		<NumerickaKlavesnice>ano</NumerickaKlavesnice>
    		<OptickaMechanika>ano</OptickaMechanika>
    		<CteckaOtiskuPrstu>ne</CteckaOtiskuPrstu>
    		<DotykovyDisplej>ne</DotykovyDisplej>
    	</Vybava>
        <OS TypOS="Windows" VerzeOS="10 Home"/>
    </notebook>
     <notebook>
    	<Vyrobce>Lenovo</Vyrobce>
    	<Typ>Legion Y720-15IKB</Typ>
        <Barva>černá</Barva>
    	<Prodej>
    	    <Cena mena="Kč">42990</Cena>
    		<Alza>ano</Alza>
    		<Mall>ano</Mall>
    		<CZC.cz>ano</CZC.cz>
    		<Datart>ne</Datart>
    		<Mironet>ano</Mironet>
    	</Prodej>
    	<Displej>
    	    <Uhlopricka>15.6"</Uhlopricka>
    	    <Rozliseni>1920x1080</Rozliseni>
    		<TypPanelu>IPS</TypPanelu>
    	    <TypDispleje>Antireflexní</TypDispleje>
    	</Displej>
         <Rozmery Výška="265" Šířka="380" Hloubka="25.8"/>
         <Hmotnost Hmotnost="2600"/>
    	<Baterie Kapacita="60"/>
    	<Vykon>
    	    <FrekvenceProcesoru jednotky="mHz">2800</FrekvenceProcesoru>
    		<PocetJader rozmezi="1-8">4</PocetJader>
    	    <TypProcesoru vyrobce="Intel">Intel Core i7 7700HQ</TypProcesoru>
    	    <PametRAM velikost="GB">16</PametRAM>
    	    <TypPameti>DDR4</TypPameti>
    	    <Harddisk velikost="GB">1256</Harddisk>
    	    <TypHDD>HDD + SSD</TypHDD>
    	    <GrafickaKarta velikost="GB">6</GrafickaKarta>
       		<TypGrafiky>NVIDEA</TypGrafiky>
    	</Vykon>
         <Vystupy>
    		<USB2.0>ano</USB2.0>
    		<USB3.0>ano</USB3.0>
    		<HDMI>ano</HDMI>
    		<DVI>ne</DVI>
    		<VGA>ano</VGA>
    		<Jack3.5mm>ano</Jack3.5mm>
             <LAN>ano</LAN>
    	</Vystupy>
    	<Vybava>
    		<Wifi>ano</Wifi>
    		<Bluetooth>ano</Bluetooth>
    		<OperacniSystem>ano</OperacniSystem>
    		<PodsvicenaKlavesnice>ano</PodsvicenaKlavesnice>
    		<CteckaKaret>ano</CteckaKaret>
    		<NumerickaKlavesnice>ano</NumerickaKlavesnice>
    		<OptickaMechanika>ano</OptickaMechanika>
    		<CteckaOtiskuPrstu>ne</CteckaOtiskuPrstu>
    		<DotykovyDisplej>ne</DotykovyDisplej>
    	</Vybava>
         <OS TypOS="Windows" VerzeOS="10 Home"/>
    </notebook>
     <notebook>
    	<Vyrobce>ASUS</Vyrobce>
    	<Typ>ZENBOOK UX410UA-GV017T</Typ>
        <Barva>stříbrná</Barva>
    	<Prodej>
    	    <Cena mena="Kč">16990</Cena>
    		<Alza>ano</Alza>
    		<Mall>ano</Mall>
    		<CZC.cz>ne</CZC.cz>
    		<Datart>ne</Datart>
    		<Mironet>ano</Mironet>
    	</Prodej>
    	<Displej>
    	    <Uhlopricka>14"</Uhlopricka>
    	    <Rozliseni>1920x1080</Rozliseni>
    		<TypPanelu>IPS</TypPanelu>
    	    <TypDispleje>Antireflexní</TypDispleje>
    	</Displej>
    	<Rozmery Výška="256" Šířka="323" Hloubka="223"/>
    	<Hmotnost Hmotnost="1450"/>
    	<Baterie Kapacita="48"/>
    	<Vykon>
    	    <FrekvenceProcesoru jednotky="mHz">2400</FrekvenceProcesoru>
    	    <PocetJader rozmezi="1-8">2</PocetJader>
    	    <TypProcesoru vyrobce="Intel">Core i3 7100U</TypProcesoru>
    	    <PametRAM velikost="GB">4</PametRAM>
    		<TypPameti>DDR4</TypPameti>
    	    <Harddisk velikost="GB">128</Harddisk>
    		<TypHDD>SSD</TypHDD>
    	    <GrafickaKarta velikost="GB">2</GrafickaKarta>
    		<TypGrafiky>Intel</TypGrafiky>
    	</Vykon>
    	<Vystupy>
    		<USB2.0>ano</USB2.0>
    		<USB3.0>ano</USB3.0>
    		<HDMI>ano</HDMI>
    		<DVI>ne</DVI>
    		<VGA>ano</VGA>
    		<Jack3.5mm>ano</Jack3.5mm>
    		<LAN>ne</LAN>
    	</Vystupy>
    	<Vybava>
    		<Wifi>ano</Wifi>
    		<Bluetooth>ano</Bluetooth>
    		<OperacniSystem>ano</OperacniSystem>
    		<PodsvicenaKlavesnice>ano</PodsvicenaKlavesnice>
    		<CteckaKaret>ano</CteckaKaret>
    		<NumerickaKlavesnice>ne</NumerickaKlavesnice>
    		<OptickaMechanika>ne</OptickaMechanika>
    		<CteckaOtiskuPrstu>ne</CteckaOtiskuPrstu>
    		<DotykovyDisplej>ne</DotykovyDisplej>
    	</Vybava>
         <OS TypOS="Windows" VerzeOS="10 Home"/>
    </notebook>
    <notebook>
        <Vyrobce>HP</Vyrobce>
        <Typ>ProBook 430 G4</Typ>
        <Barva>stříbrná</Barva>
        <Prodej>
            <Cena mena="Kč">22990</Cena>
            <Alza>ano</Alza>
            <Mall>ano</Mall>
            <CZC.cz>ano</CZC.cz>
            <Datart>ano</Datart>
            <Mironet>ano</Mironet>
        </Prodej>
        <Displej>
            <Uhlopricka>13.3"</Uhlopricka>
            <Rozliseni>1920x1080</Rozliseni>
            <TypPanelu>IPS</TypPanelu>
            <TypDispleje>Antireflexní</TypDispleje>
        </Displej>
        <Rozmery Výška="19.8" Šířka="330" Hloubka="233.5"/>
        <Hmotnost Hmotnost="1500"/>
        <Baterie Kapacita="48"/>
        <Vykon>
            <FrekvenceProcesoru jednotky="mHz">2500</FrekvenceProcesoru>
            <PocetJader rozmezi="1-8">2</PocetJader>
            <TypProcesoru vyrobce="Intel">Intel Core i5 7200U</TypProcesoru>
            <PametRAM velikost="GB">4</PametRAM>
            <TypPameti>DDR4</TypPameti>
            <Harddisk velikost="GB">256</Harddisk>
            <TypHDD>SSD</TypHDD>
            <GrafickaKarta velikost="GB">2</GrafickaKarta>
            <TypGrafiky>Intel</TypGrafiky>
        </Vykon>
        <Vystupy>
            <USB2.0>ano</USB2.0>
            <USB3.0>ano</USB3.0>
            <HDMI>ano</HDMI>
            <DVI>ne</DVI>
            <VGA>ano</VGA>
            <Jack3.5mm>ano</Jack3.5mm>
            <LAN>ne</LAN>
        </Vystupy>
        <Vybava>
            <Wifi>ano</Wifi>
            <Bluetooth>ano</Bluetooth>
            <OperacniSystem>ano</OperacniSystem>
            <PodsvicenaKlavesnice>ano</PodsvicenaKlavesnice>
            <CteckaKaret>ano</CteckaKaret>
            <NumerickaKlavesnice>ne</NumerickaKlavesnice>
            <OptickaMechanika>ne</OptickaMechanika>
            <CteckaOtiskuPrstu>ne</CteckaOtiskuPrstu>
            <DotykovyDisplej>ne</DotykovyDisplej>
        </Vybava>
        <OS TypOS="Windows" VerzeOS="10 Pro"/>
    </notebook>
    <notebook>
        <Vyrobce>DELL</Vyrobce>
        <Typ>Inspiron 15 (7000) Gaming Black</Typ>
        <Barva>černý</Barva>
        <Prodej>
            <Cena mena="Kč">42190</Cena>
            <Alza>ano</Alza>
            <Mall>ano</Mall>
            <CZC.cz>ano</CZC.cz>
            <Datart>ne</Datart>
            <Mironet>ne</Mironet>
        </Prodej>
        <Displej>
            <Uhlopricka>15.6"</Uhlopricka>
            <Rozliseni>3840x2160</Rozliseni>
            <TypPanelu>IPS</TypPanelu>
            <TypDispleje>Antireflexní</TypDispleje>
        </Displej>
        <Rozmery Výška="25.3" Šířka="383" Hloubka="265"/>
        <Hmotnost Hmotnost="2720"/>
        <Baterie Kapacita="74"/>
        <Vykon>
            <FrekvenceProcesoru jednotky="mHz">2800</FrekvenceProcesoru>
            <PocetJader rozmezi="1-8">4</PocetJader>
            <TypProcesoru vyrobce="Intel">Intel Core i7 7700HQ</TypProcesoru>
            <PametRAM velikost="GB">16</PametRAM>
            <TypPameti>DDR4</TypPameti>
            <Harddisk velikost="GB">512</Harddisk>
            <TypHDD>SSD</TypHDD>
            <GrafickaKarta velikost="GB">4</GrafickaKarta>
            <TypGrafiky>Intel</TypGrafiky>
        </Vykon>
        <Vystupy>
            <USB2.0>ano</USB2.0>
            <USB3.0>ano</USB3.0>
            <HDMI>ano</HDMI>
            <DVI>ne</DVI>
            <VGA>ano</VGA>
            <Jack3.5mm>ano</Jack3.5mm>
            <LAN>ne</LAN>
        </Vystupy>
        <Vybava>
            <Wifi>ano</Wifi>
            <Bluetooth>ano</Bluetooth>
            <OperacniSystem>ano</OperacniSystem>
            <PodsvicenaKlavesnice>ano</PodsvicenaKlavesnice>
            <CteckaKaret>ano</CteckaKaret>
            <NumerickaKlavesnice>ano</NumerickaKlavesnice>
            <OptickaMechanika>ne</OptickaMechanika>
            <CteckaOtiskuPrstu>ne</CteckaOtiskuPrstu>
            <DotykovyDisplej>ne</DotykovyDisplej>
        </Vybava>
        <OS TypOS="Windows" VerzeOS="10 Pro"/>
    </notebook>
</katalog>
